services:
  - type: web
    name: web-bit-creator
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: DELIVERY_MODE
        value: providers
